name: "Pull Request Triage"
on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      # Grab sources to get update_reviewers.py and reviewers.yml
      - name: Fetch sources
        uses: actions/checkout@v3
        with:
          # Ensure we pin the source origin as pull_request_target run under forks.
          fetch-depth: 0
          repository: Ryujinx/Ryujinx
          ref: master

      - name: Update labels based on changes
        uses: actions/labeler@v4
        with:
          sync-labels: true
          dot: true

      - name: Assign reviewers
        if: ! github.event.pull_request.draft
        run: |
          pip3 install PyGithub
          python3 .github/update_reviewers.py ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} ${{ github.event.pull_request.number }} .github/reviewers.yml
        shell: bash
